<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AllowancesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        DB::table('allowances')->insert([
            [
                'currency_id' => 75,
                'name' => 'Cook / House',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Servant',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Gardener',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Ayah',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Watchman (D)',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Watchman (N)',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Furniture',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Water',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 500,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Telephone',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Electricity',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 1500,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Security System',
                'non_cash' => true,
                'type' => 'per_employee',
                'rate' => 0,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Saloon Hatch Backs and Estates Up to 1200 cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 3600,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Saloon Hatch Backs and Estates 1201 to 1500 cc',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 4200,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Saloon Hatch Backs and Estates 1501 to 1750 cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 5800,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Saloon Hatch Backs and Estates 1751 to 2000 cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 7200,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Saloon Hatch Backs and Estates 2001 to 3000 cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 8600,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Saloon Hatch Backs and Estates Over 3000 cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 14400,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Pick-ups, Panel Van Unconverted Up to 1750cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 3600,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Pick-ups, Panel Van Unconverted Over 1750 cc.',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 4200,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'currency_id' => 75,
                'name' => 'Land Rovers/Cruisers',
                'non_cash' => true,
                'type' => 'rate',
                'rate' => 7200,
                'taxable' => true,
                'tax_rate' => 100,
                'has_relief' => false,
                'in_basic' => false,
                'system_install' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}